"""empty message

Revision ID: 240b95254f23
Revises: c4edc2651d7b
Create Date: 2023-02-23 00:06:22.049725

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "240b95254f23"
down_revision = "c4edc2651d7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
